#!/bin/ksh

typeset -i SETU=1
typeset -i SETX=0

function delay {
  [ ${SETX} -eq 0 ] || set -x

  sleep 5
}

function up {
  [ ${SETX} -eq 0 ] || set -x
  [ ${#} -eq 1 ] || return 1

  { until httping -I'appwait' -sq -c1 -t5 -g "http://${1}/login.jsp" ; do
      delay ${?}
    done
  } >/dev/null 2>&1

  return 0
}

function down {
  [ ${SETX} -eq 0 ] || set -x
  [ ${#} -eq 1 ] || return 1

  { while httping -I'appwait' -sq -c1 -t5 -g "http://${1}/login.jsp" ; do
      delay ${?}
    done
  } >/dev/null 2>&1

  return 0
}

while getopts 'dux' OPT ; do
  case "${OPT}" in
    d) SETU=0 ;;
    u) SETU=1 ;;
    x) SETX=1 ;;
    ?) exit 1 ;;
  esac
done
shift $((OPTIND-1))
[ ${SETX} -eq 0 ] || set -x

[ ${#} -eq 0 ] && {
  echo 'Usage: appwait [-ud] [-x] <host|ip> ...' >&2
  exit 1
}

for HOST in "$@" ; do
  [ ${SETU} -eq 0 ] && down "${HOST}"
  [ ${SETU} -ne 0 ] &&   up "${HOST}"
done

exit 0
